# Generated by Django 4.2.7 on 2023-12-03 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_feedback_alter_image_image_alter_image_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='surname',
        ),
    ]
