# Generated by Django 4.2.7 on 2024-03-24 17:25

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_feedback_surname'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('image', models.ImageField(upload_to=main.models.get_image_path, verbose_name='Изображение')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
